version: "3"

services:
  client:
    build:
      context: ./client
    ports:
      - "3007:3007"
    command: npm run start
  server:
    build:
      context: ./server
    volumes:
      - "./server:/usr/src/app"
    ports:
      - "3008:3008"
    command: npm start
